CREATE TABLE IF NOT EXISTS "role" (
	"name" CHARACTER VARYING(255) PRIMARY KEY,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "tariff" (
    "name" CHARACTER VARYING(255) PRIMARY KEY,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "user" (
    "id" BIGSERIAL NOT NULL PRIMARY KEY,
    "name" CHARACTER VARYING(100) NOT NULL,
    "last_name" CHARACTER VARYING(100) NOT NULL,
    "middle_name" CHARACTER VARYING(100),
    "email" CHARACTER VARYING(255) NOT NULL UNIQUE,
    "phone" CHARACTER VARYING(11) NOT NULL UNIQUE,
	-- сделать реализацию SET DEFAULT на стороне приложения
	"tariff" CHARACTER VARYING(255) REFERENCES "tariff" ON UPDATE CASCADE ON DELETE SET NULL,
	"inn" CHARACTER VARYING(12),
	"snils" CHARACTER VARYING(11) NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "service" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "employee" (
	"id" BIGSERIAL NOT NULL PRIMARY KEY,
	"name" CHARACTER VARYING(100) NOT NULL,
    "last_name" CHARACTER VARYING(100) NOT NULL,
    "middle_name" CHARACTER VARYING(100),
    "email" CHARACTER VARYING(255) NOT NULL UNIQUE,
	"role" CHARACTER VARYING(255) REFERENCES "role" ON UPDATE CASCADE ON DELETE RESTRICT,
	"active" BOOLEAN NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "employee_specs" (
	"id" BIGSERIAL NOT NULL PRIMARY KEY,
	"employee_id" BIGINT NOT NULL REFERENCES "employee" ON DELETE CASCADE,
	"service_id" INTEGER NOT NULL REFERENCES "service" ON DELETE CASCADE,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	UNIQUE ("employee_id", "service_id")

);

CREATE TABLE IF NOT EXISTS "request" (
	"id" BIGSERIAL NOT NULL PRIMARY KEY,
	"name" CHARACTER VARYING(255) NOT NULL,
	"service_id" INTEGER REFERENCES "service" ON DELETE SET NULL,
	"owner_id" BIGINT NOT NULL REFERENCES "user" ON DELETE CASCADE,
	"employee_id" BIGINT REFERENCES "employee" ON DELETE SET NULL,
	"priority" CHARACTER VARYING(7) NOT NULL,
	"desc" TEXT NOT NULL,
	"status" SMALLINT NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	"desired_at" TIMESTAMPTZ,
	"closed_at" TIMESTAMPTZ
);